name: Run-Tests-and-Generate-Report

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies for Matplotlib
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libpng-dev

      - name: Install Python and CML dependencies
        run: |
          pip install -r requirements.txt
          pip install cml

      - name: Run tests and generate report
        run: |
          pytest --verbose tests/ > report.txt

      - name: Create CML report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## 📊 Iris Pipeline Sanity Check" > report.md
          echo "### Pytest Results" >> report.md
          echo "```" >> report.md
          cat report.txt >> report.md
          echo "```" >> report.md
          echo "### Model Evaluation" >> report.md
          echo "![Confusion Matrix](confusion_matrix.png)" >> report.md
          
          cml comment create report.md
